server:
  port: 8082
spring:
  application:
    name: consul-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        hostname: localhost
        service-name: ${spring.application.name}
        tags: version=1.0,author=JackyChen
        health-check-path: /actuator/health
        health-check-interval: 60s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

